/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant
    Soft IP Version: 1.0.0
    Sun Nov 25 22:20:59 2018
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module jive_bootrom (clk_i, clk_en_i, wr_en_i, wr_data_i, addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  wr_en_i;
    input  [31:0]  wr_data_i;
    input  [7:0]  addr_i;
    output  [31:0]  rd_data_o;
endmodule